services:
  app:
    build: .
    ports:
      - "2999:2999"
    volumes:
      - .:/usr/src/web             
      - /usr/src/web/node_modules
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=webpython
    depends_on:
      - db
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: webpython
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: